import{i,a as S,S as q}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&m(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function m(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const h=document.querySelector(".form"),p=document.querySelector(".gallery"),v=document.querySelector("div"),$=document.querySelector("input"),d=document.querySelector(".btn-load"),g=()=>{const e=document.createElement("span");e.classList.add("loader"),v.append(e)},a=()=>{const e=document.querySelector(".loader");e&&e.remove()},E=()=>{d.style.display="block"},l=()=>{d.style.display="none"};let u=1,y=15,f="",b,n;h.addEventListener("submit",async e=>{u=1,g(),p.innerHTML=" ",e.preventDefault();try{f=$.value;const r=await w();L(r),h.reset(),a(),E(),r.hits.length<15&&l(),r.hits.length===0&&(l(),i.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"topRight"}))}catch{i.error({title:"Error"})}});d.addEventListener("click",async()=>{g();try{u+=1;const e=await w();L(e),a();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),(p.children.length>=b||e.hits.length<y)&&(i.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter"}),l())}catch{i.error({title:"Error"}),a()}});async function w(){try{const e="42271684-72e9093d4988315267462c0c1",r=new URLSearchParams({key:e,q:f,image_type:"photo",orientation:"horizontal",safesearch:!0,page:u,per_page:y}),o=await S.get(`https://pixabay.com/api/?${r}`);return b=o.data.totalHits,o.data}catch(e){throw console.log(e),e}}function L(e){const r=e.hits.map(o=>`
            <li class="gallery-item"><a href="${o.largeImageURL}">
          <img class="gallery-image" src="${o.webformatURL}" alt="${o.tags}"></a>
          <p><b>Likes: </b>${o.likes}</p>
          <p><b>Views: </b>${o.views}</p>
          <p><b>Comments: </b>${o.comments}</p>
          <p><b>Downloads: </b>${o.downloads}</p>
          </li>`).join("");p.insertAdjacentHTML("beforeend",r),n&&n.destroy(),n=new q(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}),n.on("show.simplelightbox").refresh(),a()}
//# sourceMappingURL=commonHelpers.js.map
