import{a as S,S as q,i}from"./assets/vendor-64b55ca9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function f(t,r,n){try{const s=new URLSearchParams({key:"42271684-72e9093d4988315267462c0c1",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n});return(await S.get(`https://pixabay.com/api/?${s}`)).data}catch(s){throw console.log(s),s}}function b(t,r,n){const s=t.hits.map(e=>`
            <li class="gallery-item"><a href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}"></a>
          <p><b>Likes: </b>${e.likes}</p>
          <p><b>Views: </b>${e.views}</p>
          <p><b>Comments: </b>${e.comments}</p>
          <p><b>Downloads: </b>${e.downloads}</p>
          </li>`).join("");r.insertAdjacentHTML("beforeend",s),n&&n.destroy(),n=new q(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",fadeSpeed:150,captionSelector:"img",captionDelay:250}),n.on("show.simplelightbox").refresh()}const y=document.querySelector(".form"),a=document.querySelector(".gallery"),v=document.querySelector("div"),$=document.querySelector("input"),h=document.querySelector(".btn-load"),w=()=>{const t=document.createElement("span");t.classList.add("loader"),v.append(t)},p=()=>{const t=document.querySelector(".loader");t&&t.remove()},E=()=>{h.style.display="block"},u=()=>{h.style.display="none"};let c=1,d=15,m,g,L;y.addEventListener("submit",async t=>{c=1,w(),a.innerHTML=" ",t.preventDefault();try{m=$.value;const r=await f(m,c,d);b(r,a,L),y.reset(),p(),E(),r.hits.length<15&&u(),r.hits.length===0&&(u(),i.error({message:"Sorry, there are no images matching <br>your search query. Please try again!</br>",position:"topRight"}))}catch(r){console.log(r),i.error({title:"Error"})}});h.addEventListener("click",async()=>{w();try{c+=1;const t=await f(m,c,d);g=t.totalHits,b(t,a,L),p();const{height:r}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),(a.children.length>=g||t.hits.length<d)&&(i.warning({message:"We are sorry, but you have reached the end of search results.",position:"bottomCenter"}),u())}catch(t){console.error(t),i.error({title:"Error"}),p()}});
//# sourceMappingURL=commonHelpers.js.map
